name: Build and Deploy

on:
  pull_request:
    branches: 
      - master
    types: ['closed']

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV: production 
      REACT_APP_FIREBASE_API_KEY:  ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      REACT_APP_AUTH_DOMAIN:  ${{ secrets.REACT_APP_AUTH_DOMAIN }} 
      REACT_APP_DATABASE_URL:  ${{ secrets.REACT_APP_DATABASE_URL }} 
      REACT_APP_PROJECT_ID:  ${{ secrets.REACT_APP_PROJECT_ID }} 
      REACT_APP_STORAGE_BUCKET:  ${{ secrets.REACT_APP_STORAGE_BUCKET }} 
      REACT_APP_MESSENGER_SENDER_ID:  ${{ secrets.REACT_APP_MESSENGER_SENDER_ID }} 
      REACT_APP_APP_ID:  ${{ secrets.REACT_APP_ID }} 
      REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }} 
      REACT_APP_ADMIN_EMAIL: ${{ secrets.REACT_APP_ADMIN_EMAIL }} 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Use production project
        uses: w9jds/firebase-action@master
        with:
          args: use alecng-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set Firebase hosting deploy target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting cms alecng-cms
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cms
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
